"""Read-only aggregation of locally generated quality and security evidence."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from xml.etree import ElementTree


class QualityEvidenceInspector:
    """Parse test-tool artifacts without inferring or manufacturing results."""

    _JSON_REPORTS = {
        "coverage": "coverage-summary.json",
        "accessibility": "accessibility-summary.json",
        "performance": "performance-summary.json",
        "sast": "bandit-report.json",
        "dependencies": "dependency-audit.json",
    }

    def __init__(self, evidence_root: Path) -> None:
        self.evidence_root = evidence_root.resolve()

    def workspace(self) -> dict[str, object]:
        suites = self._junit()
        reports = {name: self._json_report(filename) for name, filename in self._JSON_REPORTS.items()}
        failed_runs = [
            {
                "suite": suite["name"],
                "failures": suite["failures"],
                "errors": suite["errors"],
                "timestamp": suite["timestamp"],
            }
            for suite in suites
            if int(suite["failures"]) + int(suite["errors"]) > 0
        ]
        return {
            "collected_at": datetime.now(UTC).isoformat(),
            "source": "generated_test_artifacts",
            "test_status": self._test_status(suites),
            "failed_runs": failed_runs,
            "security_findings": {
                "sast": reports["sast"],
                "dependencies": reports["dependencies"],
            },
            "coverage_summary": reports["coverage"],
            "accessibility": reports["accessibility"],
            "performance": reports["performance"],
            "suites": suites,
            "limitations": [
                "Only files generated by test and security tools are reported.",
                "Missing, invalid, or expired evidence is reported as unavailable.",
                "External CI history requires an authenticated provider integration.",
            ],
        }

    def _junit(self) -> list[dict[str, object]]:
        path = self.evidence_root / "junit.xml"
        if not path.is_file():
            return []
        try:
            root = ElementTree.parse(path).getroot()
        except (OSError, ElementTree.ParseError):
            return []
        nodes = [root] if root.tag == "testsuite" else list(root.findall("testsuite"))
        return [
            {
                "name": node.get("name") or "test suite",
                "tests": int(node.get("tests") or 0),
                "failures": int(node.get("failures") or 0),
                "errors": int(node.get("errors") or 0),
                "skipped": int(node.get("skipped") or 0),
                "duration_seconds": float(node.get("time") or 0),
                "timestamp": node.get("timestamp"),
                "status": "failed" if int(node.get("failures") or 0) + int(node.get("errors") or 0) else "passed",
            }
            for node in nodes
        ]

    @staticmethod
    def _test_status(suites: list[dict[str, object]]) -> dict[str, object]:
        if not suites:
            return {"status": "unavailable", "detail": "No JUnit evidence has been generated."}
        totals = {key: sum(int(suite[key]) for suite in suites) for key in ("tests", "failures", "errors", "skipped")}
        totals["duration_seconds"] = round(sum(float(suite["duration_seconds"]) for suite in suites), 3)
        totals["status"] = "failed" if totals["failures"] + totals["errors"] else "passed"
        return totals

    def _json_report(self, filename: str) -> dict[str, object]:
        path = self.evidence_root / filename
        if not path.is_file():
            return {"status": "unavailable", "detail": f"{filename} has not been generated."}
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return {"status": "unavailable", "detail": f"{filename} is not valid JSON."}
        if not isinstance(payload, dict):
            return {"status": "unavailable", "detail": f"{filename} has an unsupported format."}
        return {
            "status": "available",
            "generated_at": datetime.fromtimestamp(path.stat().st_mtime, UTC).isoformat(),
            "data": payload,
        }
